### ISSUE TITLE
Compatibility with CarbonFields 3.0

### ISSUE THREAD

**Issue by Mick00** [elvishp2006/carbon-field-rest-api-select#38]
Hi, it is said to require Carbon-fields 2.2 in the composer.json, but could I make it work with Carbon Field 3.0 somehow?

**Comment by elvishp2006** [comment]
Hi, unfortunately, It's not compatible with CF 3.0 yet, the code needs to be almost all rewrote to get it working.

**Comment by Mick00** [comment]
Ok, good to know
